<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="." tests="10" assertions="9" failures="3" errors="1" time="0.104327">
    <testsuite name="Calculator2Test" file="/home/gapon/NetBeansProjects/PhpProject01/tests/hola/Calculator2Test.php" tests="5" assertions="5" failures="0" errors="0" time="0.053683">
      <testcase name="testAdd" class="Calculator2Test" file="/home/gapon/NetBeansProjects/PhpProject01/tests/hola/Calculator2Test.php" line="43" assertions="1" time="0.012064"/>
      <testcase name="testAdd2" class="Calculator2Test" file="/home/gapon/NetBeansProjects/PhpProject01/tests/hola/Calculator2Test.php" line="54" assertions="1" time="0.011340"/>
      <testcase name="testAdd3" class="Calculator2Test" file="/home/gapon/NetBeansProjects/PhpProject01/tests/hola/Calculator2Test.php" line="65" assertions="1" time="0.009345"/>
      <testcase name="testAdd4" class="Calculator2Test" file="/home/gapon/NetBeansProjects/PhpProject01/tests/hola/Calculator2Test.php" line="76" assertions="1" time="0.010529"/>
      <testcase name="testAdd5" class="Calculator2Test" file="/home/gapon/NetBeansProjects/PhpProject01/tests/hola/Calculator2Test.php" line="87" assertions="1" time="0.010405"/>
    </testsuite>
    <testsuite name="NoTestClassTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/NoTestClassTest.php" tests="0" assertions="0" failures="0" errors="0" time="0.000000"/>
    <testsuite name="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" tests="5" assertions="4" failures="3" errors="1" time="0.050644">
      <testcase name="testAdd" class="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" line="43" assertions="1" time="0.010049"/>
      <testcase name="testAdd2" class="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" line="54" assertions="1" time="0.010038">
        <failure type="PHPUnit_Framework_ExpectationFailedException">testAdd2(CalculatorTest)
Failed asserting that two objects are equal.
--- Expected
+++ Actual
@@ -1,3 +1 @@
-MyObject Object
-(
-)
+77
\ Chybí znak konce řádku na konci souboru


/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php:56
</failure>
      </testcase>
      <testcase name="testAdd3" class="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" line="62" assertions="1" time="0.010117">
        <failure type="PHPUnit_Framework_ExpectationFailedException">testAdd3(CalculatorTest)
my expected message
Failed asserting that two strings are equal.
expected string &lt;hello&gt;
difference      &lt; x???&gt;
got string      &lt;hi&gt;

/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php:64
</failure>
      </testcase>
      <testcase name="testAdd4" class="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" line="70" assertions="1" time="0.010406">
        <failure type="PHPUnit_Framework_ExpectationFailedException">testAdd4(CalculatorTest)
Failed asserting that &lt;integer:2&gt; matches expected value &lt;integer:3&gt;.

/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php:75
</failure>
      </testcase>
      <testcase name="testAdd5" class="CalculatorTest" file="/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php" line="78" assertions="0" time="0.010034">
        <error type="Exception">testAdd5(CalculatorTest)
Exception: my exception

/home/gapon/NetBeansProjects/PhpProject01/src/Calculator.php:13
/home/gapon/NetBeansProjects/PhpProject01/tests/CalculatorTest.php:82
</error>
      </testcase>
    </testsuite>
  </testsuite>
</testsuites>
